In [10]:
import numpy as np

### What to do
2 by 2
[[],[],
[],[]]
(black card, p1 cards, p2 cards)

In [40]:
def func2by2(c, a, b):
    a1, a2 = a[0], a[1]
    b1, b2 = b[0], b[1]
    c1, c2 = c[0], c[1]
    
    payout_a = np.zeros((2,2))
    payout_b = np.zeros((2,2))
    
    for i, x in enumerate(a):
        for j, y in enumerate(b):
            if x > y:
                payout_a[i,j] += c1
                payout_a[(i+1)%2,(j+1)%2] += c2
            elif x == y:
                payout_a[i,j] += c1/2
                payout_b[i,j] += c1/2
                payout_a[(i+1)%2,(j+1)%2] += c2/2
                payout_b[(i+1)%2, (j+1)%2] += c2/2
            else:
                payout_b[i,j] += c1
                payout_b[(i+1)%2,(j+1)%2] += c2
    
    A, B = np.ones((2,2)), np.ones((2,2))
    A[1,0], A[1,1] = payout_b[0,0]-payout_b[0,1], payout_b[1,0]-payout_b[1,1]
    B[1,0], B[1,1] = payout_a[0,0]-payout_a[1,0], payout_a[0,1]-payout_a[1,1]
    
    return payout_a, payout_b, A, B

In [128]:
def dominationcheck(X, m):
    nrows = X.shape[0]
    ncols = X.shape[1]

    output = []
    if m == 'cols':
        for i in range(0, ncols-1):
            for j in range(i+1, ncols):
                index1 = (X[:, i] < X[:, j]).sum()
                index2 = (X[:, i] > X[:, j]).sum()
                
                if index1 == nrows:
                    output.append(i)
                if index2 == nrows:
                    output.append(j)

    elif m == 'rows':
        for i in range(0, nrows-1):
            for j in range(i+1, nrows):
                index1 = (X[i, :] < X[j, :]).sum()
                index2 = (X[i, :] > X[j, :]).sum()

                if index1 == ncols:
                    output.append(i)
                if index2 == ncols:
                    output.append(j)

    return output

In [129]:
def dominationdelete(A, B):
    rows = dominationcheck(A, 'rows')
    cols = dominationcheck(B, 'cols')
    A = np.delete(A, rows, axis=0)
    A = np.delete(A, cols, axis=1)
    B = np.delete(B, rows, axis=0)
    B = np.delete(B, cols, axis=1)
    return A, B

In [134]:
def dominationfinal(A, B):
    while (A.shape != dominationdelete(A, B)[0].shape) and (B.shape != dominationdelete(A, B)[1].shape) :
        A, B = dominationdelete(A, B)
    return A, B

In [142]:
A, B = func2by2([2,1], [1,4], [2,3])[0], func2by2([2,1], [1,4], [2,3])[1]
print(A)
print(B)
dominationfinal(A, B)


[[1. 1.]
 [2. 2.]]
[[2. 2.]
 [1. 1.]]


(array([[2., 2.]]), array([[1., 1.]]))

In [138]:
A = np.array([[18, 15, 9],
             [20, 16, 8],
             [18, 12, 0]])
B = np.array([[18, 20, 18],
             [15, 16, 12],
             [9, 8, 0]])
dominationfinal(A, B)

(array([[16]]), array([[16]]))

In [37]:
np.linalg.solve(tt, np.array([1,0]))

array([-1.,  2.])

In [ ]:
1 4 2
3 3 1
4 5 4

In [ ]:
Nig